In [ ]:
Creating a two-layer neural network using Pytorch
- Input layer 1*3
- Linear Layer - in_features = 3, out_features = 2
- Output 1*2

In [6]:
import torch
import torch.nn as nn
#Input layer
input_layer = torch.tensor([0.414, 0.173, 0.223])

#Linear layer -> takes the first input layer values and produces a linear function
linear_layer = nn.Linear(in_features = 3, out_features = 2)
output = linear_layer(input_layer) #output = W0 @ input + b0 -> randomly assigned weights and biases
print(output)

tensor([-0.5337,  0.0560], grad_fn=<ViewBackward0>)


More linear layers

In [7]:
model = nn.Sequential(
    nn.Linear(3,6),
    nn.Linear(6,8),
    nn.Linear(8,2)
)

In [8]:
input_tensor = torch.rand(1,3)

In [9]:
output_tensor = model(input_tensor)
output_tensor

tensor([[0.0272, 0.4170]], grad_fn=<AddmmBackward0>)

Non-Linear Layers using Activation Function for complex relationships

In [11]:
#Sigmoid function for binary classification tasks, used as the last layer
import torch
import torch.nn as nn

input_tensor = torch.tensor([[9.0]])
sigmoid = nn.Sigmoid()
output = sigmoid(input_tensor)

In [12]:
output

tensor([[0.9999]])

In [13]:
#Softmax for multiclass classification and outputs a probability distribution

input_tensor = torch.tensor([[0.6, 0.7, 0.8]])
probabilities = nn.Softmax(dim = -1) #Applied along last dimension
output_tensor = probabilities(input_tensor)

output_tensor

tensor([[0.3006, 0.3322, 0.3672]])

In [16]:
#Create a neural network and get the result. Just forward pass, i.e no backpropagation to update the weights and biases
input_tensor = torch.tensor([[0.6, 0.7, 0.8, 0.9]])

model = nn.Sequential(
    nn.Linear(4,6), 
    nn.Linear(6,3), 
    nn.Softmax(dim = -1))
output_tensor = model(input_tensor)

output_tensor

tensor([[0.3146, 0.4776, 0.2078]], grad_fn=<SoftmaxBackward0>)

Loss function

In [33]:

#1. Cross Entropy Loss function

import torch.nn.functional as F
from torch.nn import CrossEntropyLoss

input = torch.tensor([[0.6, 0.7, 0.8]])
one_hot_target = F.one_hot(torch.tensor([0]), input.shape[1]) #one hot encoding

criterion = CrossEntropyLoss()
output_tensor = criterion(input_tensor.double(), one_hot_target.double())

print(output_tensor)

tensor(1.2019, dtype=torch.float64)


In [35]:
#2. L1 Loss

import torch.nn.functional as F
from torch.nn import L1Loss

input = torch.tensor([[0.6, 0.7, 0.8]])
one_hot_target = F.one_hot(torch.tensor([0]), input.shape[1]) #one hot encoding

criterion = L1Loss()
output_tensor = criterion(input_tensor.double(), one_hot_target.double())

print(output_tensor)


tensor(0.6333, dtype=torch.float64)
