Pytorch is a deep learning framework

In [2]:
!pip3 install torch

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.


In [3]:
import torch

We can also use `torchvision`, `torchtext` and `torchaudio`

Tensors 
They are the primary data structure in Pytorch
Same concept as we had learned in Mathematics - 
- 1-d tensor is called a vector
- 2-d tensor is called a matrix
- More than two dimensions is called a tensor 

In [4]:
array = [[1,2,3], [4,5,6]]
tensor = torch.tensor(array)
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
import numpy as np
np_array = np.array(array)
np_tensor = torch.from_numpy(np_array)
np_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
tensor.shape

torch.Size([2, 3])

In [7]:
tensor.dtype

torch.int64

In [8]:
tensor.device

device(type='cpu')

Tensor Operations

In [9]:
A = [[2,3], [4,5]]
B = [[-2, -3], [-4, -5]]

A+B #without tensor

[[2, 3], [4, 5], [-2, -3], [-4, -5]]

In [10]:
A = torch.tensor(A)
B = torch.tensor(B)

A+B #with tensor it gives results according to matrix rules

tensor([[0, 0],
        [0, 0]])

In [11]:
A-B

tensor([[ 4,  6],
        [ 8, 10]])

In [12]:
A*B

tensor([[ -4,  -9],
        [-16, -25]])

In [13]:
B = torch.tensor([2,3,4])
A*B #Does not follow matrix multiplication rule

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [14]:
#Create an empty tensor

empty_tensor = torch.empty(3,4)
empty_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
empty_tensor.dtype

torch.float32

In [23]:
#Setting dtype explicitly

tensor_int = torch.tensor(torch.empty(3,4) , dtype = torch.int64)
tensor_int

/var/folders/7g/f3cmzpjd23l5yk1qbh33hb940000gn/T/ipykernel_3506/3153464943.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor_int = torch.tensor(torch.empty(3,4) , dtype = torch.int64)


tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

Other available datatypes include
- torch.bool
- torch.int8
- torch.uint8
- torch.int16
- torch.int32
- torch.int64
- torch.half
- torch.float
- torch.double
- torch.bfloat

In [18]:

zeros_tensor = torch.zeros(3,4)
print(zeros_tensor)
ones_tensor = torch.ones(3,4)
print(ones_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [24]:
zeros_tensor +1

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones_tensor * 2

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [27]:
threes_tensor = ones_tensor + 2

In [28]:
threes_tensor ** 2

tensor([[9., 9., 9., 9.],
        [9., 9., 9., 9.],
        [9., 9., 9., 9.]])

In [22]:
#Initializing random values to tensors

torch.manual_seed(1024)
random_tensor = torch.rand(3,4)
print(random_tensor)

random_tensor1 = torch.rand(3,4)
print(random_tensor1)

tensor([[0.8090, 0.7935, 0.2099, 0.9279],
        [0.8136, 0.7422, 0.4769, 0.4955],
        [0.3602, 0.1178, 0.7852, 0.0228]])
tensor([[0.8793, 0.1163, 0.0540, 0.5480],
        [0.2743, 0.7038, 0.8004, 0.7361],
        [0.8983, 0.3373, 0.3783, 0.7862]])


In [20]:
#Setting the same seed value again
torch.manual_seed(1024)
random_tensor_new = torch.rand(3,4)
random_tensor_new

tensor([[0.8090, 0.7935, 0.2099, 0.9279],
        [0.8136, 0.7422, 0.4769, 0.4955],
        [0.3602, 0.1178, 0.7852, 0.0228]])

According to Pytorch documentation, 
`Manually setting the RNG’s seed resets it, so that identical computations depending on random number should, in most settings, provide identical results.`

For altering tensors in place
- most of the math functions have a version with an appended underscore (_) that will alter a tensor in place.

In [30]:
#https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html#:~:text=For%20arithmetic%20operations%2C%20there%20are%20functions%20that%20behave%20similarly%3A
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.3089, 0.9617],
        [0.2606, 0.3893]])

After adding:
tensor([[1.3089, 1.9617],
        [1.2606, 1.3893]])
tensor([[1.3089, 1.9617],
        [1.2606, 1.3893]])
tensor([[0.3089, 0.9617],
        [0.2606, 0.3893]])

After multiplying
tensor([[0.0954, 0.9248],
        [0.0679, 0.1515]])
tensor([[0.0954, 0.9248],
        [0.0679, 0.1515]])


Playing with dimensions

In [31]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0) #adds a dimension of extent 1

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])
